apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.component }}
  labels:
    app.kubernetes.io/name: {{ .Values.component }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.component }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.component }}
    spec:
      serviceAccountName: {{ .Values.component }}
      volumes:
        - name: common
          emptyDir:
            sizeLimit: 5Mi
      initContainers:
        - name: roboshop-ps-init-cont
          image: 043254050286.dkr.ecr.us-east-1.amazonaws.com/roboshop-ps-init-cont:2.0.1
          env:
            - name: PARAMETERS
              value: { { .Values.PARAMETERS } }
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /common
              name: common
      containers:
        - name: {{ .Values.component }}
          image: 043254050286.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.component }}:{{ .Values.app_version }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - mountPath: /common
              name: common